[workspace]
members = ["canandmiddleware", "fifocore", "reduxfifo-standalone", "reduxfifo-util"]

[workspace.package]
version = "2027.0.0-alpha-6"
license = "LGPL-3.0-only"
authors = ["Bagholders of Redux Robotics"]
edition = "2024"
documentation = "https://github.com/Redux-Robotics/canandrepo-public"
homepage = "https://github.com/Redux-Robotics/canandrepo-public"
repository = "https://github.com/Redux-Robotics/canandrepo-public"
publish = false

[package]
name = "reduxfifo"
version.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
publish.workspace = true

[lib]
name = "reduxfifo"
crate-type = ["lib", "cdylib", "staticlib"]

[profile.release]
opt-level = 3
lto = "fat"

[profile.release.build-override]
opt-level = 3

[profile.dev]
opt-level = 3
lto = "fat"

[profile.dev.build-override]
opt-level = 3

[features]
default = ["reduxcore"]
singleton = []

jni = ["dep:jni"]
ffi = ["singleton"]
reduxcore = ["dep:jni", "singleton", "ffi"]
tokio-console = ["dep:console-subscriber"]

# prebaked feature sets for target platforms
# enables systemcore-specific behavior
systemcore = ["reduxcore", "fifocore/systemcore"]
simulation = ["reduxcore"]

[dependencies]
fifocore = { path = "fifocore" }
canandmiddleware = { path = "canandmiddleware" }

futures = "0.3.32"
jni = { version = "0.21.1", optional = true }
libc = "0.2"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1.52.3", features = ["full"] }
frc-can-id = { path = "../crates/frc-can-id" }
log = "0.4.33"
parking_lot = { version = "0.12.5", features = [] }
env_logger = "0.11.11"
console-subscriber = { version = "0.5.0", features = ["parking_lot"], optional = true }

[build-dependencies]
build-data = "0.3.3"
