package com.reduxrobotics.canand;

/**
 * Logs Redux CAN messages that are sent and received.
 */
public class MessageLogger {
    /**
     * Opens a new log file.
     * If a previous log file was open, it is closed and replaced with this one.
     * 
     * <p>
     * Passing in a directory will create a new autogenerated file name in that directory.
     * Passsing in a file name will write to that file name.
     * </p>
     * @param path path to log
     */
    public static void openLog(String path) {
        ReduxJNI.openLog(path, 0);
    }
    /**
     * Closes any open loggers.
     */
    public static void closeLog() {
        ReduxJNI.closeLog(0);
    }
}
