"""
Extracts code snippets from javadocs, stuffs them into a robot project, and checks if they compile.
"""
import bs4
from pathlib import Path
import pprint
import functools
import dataclasses
import typing
import textwrap
import shutil
import os



@dataclasses.dataclass
class DocEntry:
    # fully qualified class name
    doc_name: str
    # entry id
    idx: int
    # entry_text
    code: str

    def get_namespaces(self, namespaces: typing.List[str], using=True) -> typing.List[str]:
        """structredux_1_1frames -> using namespace redux::frames;"""
        s = None
        for prefix in ["class", "struct", "namespace"]:
            if self.doc_name.startswith(prefix):
                s = self.doc_name[len(prefix):]
                break
        
        v = []
        for namespace in namespaces:
            if s.startswith(namespace):
                namespace = namespace.replace("_1", ":")
                if using:
                    v.append(f'using namespace {namespace};')
                else:
                    v.append(namespace)
        
        if using:
            return "\n".join(v)
        return v

    def generate_snippet(self, namespaces: typing.List[str]) -> str:
        return f"""
void {self.doc_name}__{self.idx}() {{
{textwrap.indent(self.get_namespaces(namespaces), "    ")}

{textwrap.indent(self.code, "    ")}
}}
"""

def sanitize_name(s: str) -> str:
    v = []
    for c in s:
        if c.isalnum() or c in "$_":
            v.append(c)
        elif c == ".":
            v.append("_1")
        else:
            v.append("_")
    return "".join(v)

def get_soup(fname: Path) -> bs4.BeautifulSoup:
    with open(fname, "r") as f:
        return bs4.BeautifulSoup(f.read(), 'lxml')

def strip_ttc(soup: bs4.Tag):
    # these div tags are often in markdown code blocks and need to be removed
    # otherwise finding bits is as easy as <div class="fragment">
    tag: bs4.Tag
    for tag in soup.find_all("div", class_="ttc"):
        tag.extract()

def process_page(fname: Path, namespaces: typing.List[str]) -> typing.List[DocEntry]:
    soup = get_soup(fname)
    print("\n------ ", fname.name)
    pre: bs4.Tag
    for pre in soup.find_all("pre"):
        attrs: typing.List[str] = pre.get("class", [])
        if "not-code" in attrs:
            continue
        print("\n----- Error: <pre> tag detected that lacks class=\"not-code\": If you're using code, use Markdown ```cpp ... ``` instead")
        exit(1)
    
    tag: bs4.Tag
    docs_entry: typing.List[DocEntry] = []
    for i, tag in enumerate(soup.find_all("div", class_="fragment")):
        strip_ttc(tag)
        code = tag.get_text().strip()
        if code.startswith("= "):
            # this is likely an initial value block (skip it)
            continue
        #print(code)
        docs_entry.append(DocEntry(fname.name[:-5], i, code))
        print(docs_entry[-1].generate_snippet(namespaces))
    
    return docs_entry


def main(doxy_root: Path):
    # namespaces that cannot be "using-ed" for silliness
    namespaces = sorted((p.name[len("namespace"):-len(".html")] for p in doxy_root.glob("namespaceredux*.html")), key=len, reverse=True)

    sensors = [hdr.name for hdr in (doxy_root/"../../../src/main/native/include/redux/sensors/").glob("*.h")]
    controllers = [hdr.name for hdr in (doxy_root/"../../../src/main/native/include/redux/motorcontrol/").glob("*.h")]

    sensors = "".join([f"#include <redux/sensors/{hdr}>\n" for hdr in sensors])
    controllers = "".join([f"#include <redux/motorcontrol/{hdr}>\n" for hdr in controllers])

    docs_entry: typing.List[DocEntry] = []
    for path in sorted(doxy_root.glob("*.html")):
        if not any(map(path.name.startswith, ("classredux", "namespaceredux", "structredux"))) or path.name.endswith("-members.html"):
            continue
        docs_entry.extend(process_page(path, namespaces))
    
    template = f"""// Autogenerated snippets file

// Boilerplate
#include <fmt/format.h>

// redux::canand
#include <redux/canand/CanandAddress.h>
#include <redux/canand/CanandDevice.h>
#include <redux/canand/CanandMessage.h>
#include <redux/canand/CanandUtils.h>
#include <redux/canand/MessageBus.h>
#include <redux/frames/Frame.h>

// redux::sensors
{sensors}

// redux::motorcontrol
{controllers}
namespace snippets {{

{"".join(d.generate_snippet(namespaces) for d in docs_entry)}

}}"""
    snippets_proj_root = Path(os.path.dirname(os.path.realpath(__file__)))/"Snippets-cpp"
    with open(snippets_proj_root/"src/main/cpp/Snippets.cpp", "w") as f:
        f.write(template)



if __name__ == "__main__":
    import sys
    #doxy_root = Path("../ReduxLib/build/doxygen/html")
    main(Path(sys.argv[1]))
    #main(doxy_root)
    # sys.argv[root] should be ../ReduxLib/build/doxygen/html

    #soup = get_soup(doxy_root/"allclasses-index.html")
